### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by Tarikul-Islam-Anik**
#### **Patch Notes:**

- Implemented Dark mode.
- Change in styles.
- Minor bug fixes.

**Preview:** https://chicken-coop-nnbcf5mw3-mahadihassanriyadh.vercel.app/

@mahadihassanriyadh Bumped the version from `1.0.0` to `1.2.0`. Create a new release note.

### CODE REVIEW

**Comment by 0xriyadh** [comment]
@Tarikul-Islam-Anik the square with lab classrooms should match the color of the lab classes. Checkout the image below to understand it more clearly.
issue image

**Comment by 0xriyadh** [comment]
@Tarikul-Islam-Anik Also mention the issue in the PR description like this
**Referenced Issue:** [Feature Request]: Add Dark Mode toggle #7

**Comment by Tarikul-Islam-Anik** [comment]
@mahadihassanriyadh the color issue has been resolved and edited the PR description.

**Review by 0xriyadh — APPROVED** [review]

**Comment by mahadihassanriyadh** [comment]
@Tarikul-Islam-Anik Awesome, merging the PR #8 and closing the issue #7
Thank you for your contributions.

**Comment by 0xriyadh** [comment]
@Tarikul-Islam-Anik Awesome, merging the PR #8 and closing the issue #7
Thank you for your contributions.

**Pull request merged**
